const skills = [
  "react.svg",
  "js.svg",
  "html.svg",
  "css.svg",
  "nodejs.svg",
  "python.svg",
  "bootstrap.svg",
  "git.svg",
  "github.svg",
  "mongodb.svg",
  "tailwind.svg",
  "linux.svg",
  "php.svg",
  "jupyter.svg",
  "mysql.svg",
  "oracle.svg",
  "openstack.svg",
  "raspberrypi.svg",
  "r.svg",
  "supabase.svg",
  "vuejs.svg",
  "apache_tomcat.svg",
  "cisco.svg",
  "firebase.svg",
  "flutterio.svg",
]; // Add or remove skills here, make sure to include the image respective to the skill inside the public/skills folder and use the correct file extension

export default skills;
